// Pure mapping helpers between Supabase rows (snake_case) and the app's
// camelCase shapes defined in mock-data.ts. No secrets here — safe to import
// from both the seed script and server functions.
import type {
  Company,
  Contact,
  Deal,
  Activity,
  Screen,
  Campaign,
  Influencer,
  Lead,
} from "./mock-data";

/* ---------- DB row -> app object (read path) ---------- */

export const rowToLead = (r: any): Lead => ({
  id: r.id,
  companyName: r.company_name,
  contactName: r.contact_name ?? undefined,
  jobTitle: r.job_title ?? undefined,
  phone: r.phone ?? undefined,
  email: r.email ?? undefined,
  lineId: r.line_id ?? undefined,
  website: r.website ?? undefined,
  province: r.province ?? undefined,
  industry: r.industry ?? undefined,
  clientType: r.client_type ?? undefined,
  agencyType: r.agency_type ?? undefined,
  source: r.source ?? "Manual",
  status: r.status ?? "New",
  assignedTo: r.assigned_to ?? undefined,
  leadScore: r.lead_score ?? 0,
  aiClass: r.ai_class ?? undefined,
  estimatedBudget: r.estimated_budget ?? undefined,
  notes: r.notes ?? undefined,
  convertedCompanyId: r.converted_company_id ?? undefined,
  createdAt: r.created_at ?? undefined,
});

export const rowToCompany = (r: any): Company => ({
  id: r.id,
  name: r.name,
  type: r.type,
  subType: r.sub_type,
  industry: r.industry,
  province: r.province,
  status: r.status,
  tier: r.tier,
  leadScore: r.lead_score ?? 0,
  aiClass: r.ai_class,
  annualBudget: r.annual_budget,
  totalDealValue: Number(r.total_deal_value ?? 0),
  assignedTo: r.assigned_to,
  lastActivity: r.last_activity,
  website: r.website ?? undefined,
  phone: r.phone ?? undefined,
  size: r.size,
  source: r.source,
  tags: r.tags ?? [],
  summary: r.summary,
  clientType: r.client_type ?? r.type ?? undefined,
  agencyType: r.agency_type ?? undefined,
  partnerPotentialScore: r.partner_potential_score ?? undefined,
  estimatedAnnualMarketingBudget: r.estimated_annual_marketing_budget ?? undefined,
  numberOfBranches: r.number_of_branches ?? undefined,
  facebookUrl: r.facebook_url ?? undefined,
  instagramUrl: r.instagram_url ?? undefined,
  linkedinUrl: r.linkedin_url ?? undefined,
  tiktokUrl: r.tiktok_url ?? undefined,
});

export const rowToContact = (r: any): Contact => ({
  id: r.id,
  name: r.name,
  companyId: r.company_id,
  jobTitle: r.job_title,
  roleType: r.role_type,
  phone: r.phone,
  lineId: r.line_id,
  email: r.email,
  preferred: r.preferred,
  status: r.status,
  lastContacted: r.last_contacted,
  assignedTo: r.assigned_to,
});

export const rowToScreen = (r: any): Screen => ({
  id: r.id,
  name: r.name,
  province: r.province,
  area: r.area,
  areaType: r.area_type,
  size: r.size,
  resolution: r.resolution,
  availability: r.availability,
  rate15s: r.rate_15s ?? 0,
  rateDaily: r.rate_daily ?? 0,
  rateMonthly: r.rate_monthly ?? 0,
  dailyImpressions: r.daily_impressions ?? 0,
  audience: r.audience ?? [],
  hours: r.hours,
  ratePerSecond: r.rate_per_second != null ? Number(r.rate_per_second) : undefined,
  code: r.code ?? undefined,
  address: r.address ?? undefined,
  lat: r.lat ?? undefined,
  lng: r.lng ?? undefined,
});

export const rowToDeal = (r: any): Deal => ({
  id: r.id,
  name: r.name,
  companyId: r.company_id,
  contactId: r.contact_id,
  clientType: r.client_type,
  stage: r.stage,
  value: Number(r.value ?? 0),
  tier: r.tier,
  aiClass: r.ai_class,
  priority: r.priority,
  campaignType: r.campaign_type,
  duration: r.duration,
  screens: r.screens ?? [],
  expectedClose: r.expected_close,
  probability: r.probability ?? 0,
  nextFollowUp: r.next_follow_up,
  notes: r.notes ?? "",
});

export const rowToCampaign = (r: any): Campaign => ({
  id: r.id,
  name: r.name,
  companyId: r.company_id,
  status: r.status,
  start: r.start_date,
  end: r.end_date,
  budget: Number(r.budget ?? 0),
  impressions: Number(r.impressions ?? 0),
  cpm: Number(r.cpm ?? 0),
  satisfaction: r.satisfaction ?? "—",
  renewal: r.renewal ?? 0,
  objective: r.objective ?? undefined,
  screenIds: r.screen_ids ?? [],
  influencerIds: r.influencer_ids ?? [],
  contentPieces: r.content_pieces ?? 0,
  billboardReach: Number(r.billboard_reach ?? 0),
  influencerViews: Number(r.influencer_views ?? 0),
  socialEngagement: Number(r.social_engagement ?? 0),
  storeVisits: r.store_visits ?? 0,
  qrScans: r.qr_scans ?? 0,
  revenue: Number(r.revenue ?? 0),
  aiInsight: r.ai_insight ?? undefined,
  renewalReasons: r.renewal_reasons ?? [],
  owner: r.owner ?? undefined,
  notes: r.notes ?? undefined,
  screensPlan: r.screens_plan ?? [],
  influencersPlan: r.influencers_plan ?? [],
  deliverables: r.deliverables ?? [],
  tasks: r.tasks ?? [],
  campaignType: r.campaign_type ?? "CLIENT_ACTIVATION",
  performance: r.performance ?? {},
  influencerPerf: r.influencer_perf ?? [],
  ads: r.ads ?? [],
});

export const rowToInfluencer = (r: any): Influencer => ({
  id: r.id,
  name: r.name,
  platform: r.platform,
  followers: Number(r.followers ?? 0),
  category: r.category,
  province: r.province,
  rateCard: r.rate_card,
  avgViews: Number(r.avg_views ?? 0),
  engagementRate: Number(r.engagement_rate ?? 0),
  contentStatus: r.content_status ?? "Idle",
  brandsWorkedWith: r.brands_worked_with ?? [],
  avatar: r.avatar ?? undefined,
});

export const rowToActivity = (r: any): Activity => ({
  id: r.id,
  type: r.type,
  title: r.title,
  date: r.date,
  status: r.status,
  dealId: r.deal_id ?? undefined,
  contactId: r.contact_id ?? undefined,
  companyId: r.company_id ?? undefined,
  summary: r.summary,
  nextAction: r.next_action ?? undefined,
  duration: r.duration ?? undefined,
  assignedTo: r.assigned_to,
});

/* ---------- app object -> DB row (write path; omits undefined) ---------- */

const clean = <T extends Record<string, any>>(o: T): T => {
  const out: Record<string, any> = {};
  for (const [k, v] of Object.entries(o)) if (v !== undefined) out[k] = v;
  return out as T;
};

export const leadToRow = (l: Partial<Lead>) =>
  clean({
    id: l.id,
    company_name: l.companyName,
    contact_name: l.contactName,
    job_title: l.jobTitle,
    phone: l.phone,
    email: l.email,
    line_id: l.lineId,
    website: l.website,
    province: l.province,
    industry: l.industry,
    client_type: l.clientType,
    agency_type: l.agencyType,
    source: l.source,
    status: l.status,
    assigned_to: l.assignedTo,
    lead_score: l.leadScore,
    ai_class: l.aiClass,
    estimated_budget: l.estimatedBudget,
    notes: l.notes,
    converted_company_id: l.convertedCompanyId,
  });

export const companyToRow = (c: Partial<Company>) =>
  clean({
    id: c.id,
    name: c.name,
    type: c.type,
    sub_type: c.subType,
    industry: c.industry,
    province: c.province,
    status: c.status,
    tier: c.tier,
    lead_score: c.leadScore,
    ai_class: c.aiClass,
    annual_budget: c.annualBudget,
    total_deal_value: c.totalDealValue,
    assigned_to: c.assignedTo,
    last_activity: c.lastActivity,
    website: c.website,
    size: c.size,
    source: c.source,
    tags: c.tags,
    summary: c.summary,
    phone: c.phone,
    client_type: c.clientType,
    agency_type: c.agencyType,
    partner_potential_score: c.partnerPotentialScore,
    estimated_annual_marketing_budget: c.estimatedAnnualMarketingBudget,
    number_of_branches: c.numberOfBranches,
    facebook_url: c.facebookUrl,
    instagram_url: c.instagramUrl,
    linkedin_url: c.linkedinUrl,
    tiktok_url: c.tiktokUrl,
  });

export const contactToRow = (c: Partial<Contact>) =>
  clean({
    id: c.id,
    name: c.name,
    company_id: c.companyId,
    job_title: c.jobTitle,
    role_type: c.roleType,
    phone: c.phone,
    line_id: c.lineId,
    email: c.email,
    preferred: c.preferred,
    status: c.status,
    last_contacted: c.lastContacted,
    assigned_to: c.assignedTo,
  });

export const screenToRow = (s: Partial<Screen>) =>
  clean({
    id: s.id,
    name: s.name,
    province: s.province,
    area: s.area,
    area_type: s.areaType,
    size: s.size,
    resolution: s.resolution,
    availability: s.availability,
    rate_15s: s.rate15s,
    rate_daily: s.rateDaily,
    rate_monthly: s.rateMonthly,
    daily_impressions: s.dailyImpressions,
    audience: s.audience,
    hours: s.hours,
    rate_per_second: s.ratePerSecond,
    code: s.code,
    address: s.address,
    lat: s.lat,
    lng: s.lng,
  });

export const dealToRow = (d: Partial<Deal>) =>
  clean({
    id: d.id,
    name: d.name,
    company_id: d.companyId,
    contact_id: d.contactId,
    client_type: d.clientType,
    stage: d.stage,
    value: d.value,
    tier: d.tier,
    ai_class: d.aiClass,
    priority: d.priority,
    campaign_type: d.campaignType,
    duration: d.duration,
    screens: d.screens,
    expected_close: d.expectedClose,
    probability: d.probability,
    next_follow_up: d.nextFollowUp,
    notes: d.notes,
  });

export const campaignToRow = (c: Partial<Campaign>) =>
  clean({
    id: c.id,
    name: c.name,
    company_id: c.companyId,
    status: c.status,
    start_date: c.start,
    end_date: c.end,
    budget: c.budget,
    impressions: c.impressions,
    cpm: c.cpm,
    satisfaction: c.satisfaction,
    renewal: c.renewal,
    objective: c.objective,
    screen_ids: c.screenIds,
    influencer_ids: c.influencerIds,
    content_pieces: c.contentPieces,
    billboard_reach: c.billboardReach,
    influencer_views: c.influencerViews,
    social_engagement: c.socialEngagement,
    store_visits: c.storeVisits,
    qr_scans: c.qrScans,
    revenue: c.revenue,
    ai_insight: c.aiInsight,
    renewal_reasons: c.renewalReasons,
    owner: c.owner,
    notes: c.notes,
    screens_plan: c.screensPlan,
    influencers_plan: c.influencersPlan,
    deliverables: c.deliverables,
    tasks: c.tasks,
    campaign_type: c.campaignType,
    performance: c.performance,
    influencer_perf: c.influencerPerf,
    ads: c.ads,
  });

export const influencerToRow = (i: Partial<Influencer>) =>
  clean({
    id: i.id,
    name: i.name,
    platform: i.platform,
    followers: i.followers,
    category: i.category,
    province: i.province,
    rate_card: i.rateCard,
    avg_views: i.avgViews,
    engagement_rate: i.engagementRate,
    content_status: i.contentStatus,
    brands_worked_with: i.brandsWorkedWith,
    avatar: i.avatar,
  });

export const activityToRow = (a: Partial<Activity>) =>
  clean({
    id: a.id,
    type: a.type,
    title: a.title,
    date: a.date,
    status: a.status,
    deal_id: a.dealId,
    contact_id: a.contactId,
    company_id: a.companyId,
    summary: a.summary,
    next_action: a.nextAction,
    duration: a.duration,
    assigned_to: a.assignedTo,
  });
