/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLeadFinderRouteImport } from './routes/_app.lead-finder'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppInfluencersRouteImport } from './routes/_app.influencers'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as AppLeadsIndexRouteImport } from './routes/_app.leads.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppLeadsImportRouteImport } from './routes/_app.leads.import'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadFinderRoute = AppLeadFinderRouteImport.update({
  id: '/lead-finder',
  path: '/lead-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInfluencersRoute = AppInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppLeadsImportRoute = AppLeadsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activities': typeof AppActivitiesRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/companies': typeof AppCompaniesRoute
  '/contacts': typeof AppContactsRoute
  '/influencers': typeof AppInfluencersRoute
  '/inventory': typeof AppInventoryRoute
  '/lead-finder': typeof AppLeadFinderRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/pipeline': typeof AppPipelineRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/leads/import': typeof AppLeadsImportRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/activities': typeof AppActivitiesRoute
  '/companies': typeof AppCompaniesRoute
  '/contacts': typeof AppContactsRoute
  '/influencers': typeof AppInfluencersRoute
  '/inventory': typeof AppInventoryRoute
  '/lead-finder': typeof AppLeadFinderRoute
  '/pipeline': typeof AppPipelineRoute
  '/': typeof AppIndexRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/leads/import': typeof AppLeadsImportRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/leads': typeof AppLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/influencers': typeof AppInfluencersRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/lead-finder': typeof AppLeadFinderRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/leads/import': typeof AppLeadsImportRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/campaigns'
    | '/companies'
    | '/contacts'
    | '/influencers'
    | '/inventory'
    | '/lead-finder'
    | '/leads'
    | '/pipeline'
    | '/campaigns/$id'
    | '/leads/import'
    | '/campaigns/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activities'
    | '/companies'
    | '/contacts'
    | '/influencers'
    | '/inventory'
    | '/lead-finder'
    | '/pipeline'
    | '/'
    | '/campaigns/$id'
    | '/leads/import'
    | '/campaigns'
    | '/leads'
  id:
    | '__root__'
    | '/_app'
    | '/_app/activities'
    | '/_app/campaigns'
    | '/_app/companies'
    | '/_app/contacts'
    | '/_app/influencers'
    | '/_app/inventory'
    | '/_app/lead-finder'
    | '/_app/leads'
    | '/_app/pipeline'
    | '/_app/'
    | '/_app/campaigns/$id'
    | '/_app/leads/import'
    | '/_app/campaigns/'
    | '/_app/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-finder': {
      id: '/_app/lead-finder'
      path: '/lead-finder'
      fullPath: '/lead-finder'
      preLoaderRoute: typeof AppLeadFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/influencers': {
      id: '/_app/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof AppInfluencersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/leads/import': {
      id: '/_app/leads/import'
      path: '/import'
      fullPath: '/leads/import'
      preLoaderRoute: typeof AppLeadsImportRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsImportRoute: typeof AppLeadsImportRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsImportRoute: AppLeadsImportRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppContactsRoute: typeof AppContactsRoute
  AppInfluencersRoute: typeof AppInfluencersRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLeadFinderRoute: typeof AppLeadFinderRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppPipelineRoute: typeof AppPipelineRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCompaniesRoute: AppCompaniesRoute,
  AppContactsRoute: AppContactsRoute,
  AppInfluencersRoute: AppInfluencersRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLeadFinderRoute: AppLeadFinderRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppPipelineRoute: AppPipelineRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
